'use client';

import Link from 'next/link';

const sections = [
  {
    title: '1. Purpose and Scope',
    body:
      'These Terms of Use govern access to the CyberScan platform and the services provided with it (CMS detection, automated scans, reporting, and alerting). Creating an account or using the service means you fully accept these Terms.'
  },
  {
    title: '2. Definitions',
    list: [
      'Platform: The CyberScan SaaS used to detect CMS technologies, run scans, and generate reports.',
      'User: Any person or entity with access to the Platform.',
      'Customer: A User that benefits from a commercial agreement allowing use of the paid service.',
      'Report: Any PDF/ZIP document generated by CyberScan as part of a scan.'
    ]
  },
  {
    title: '3. Access and Acceptable Use',
    list: [
      'Users must own or be authorized to test the domains and assets submitted to CyberScan.',
      'The Platform must not be used in violation of applicable cybersecurity or data-protection laws.',
      'Customers are responsible for the confidentiality of their credentials and for every action taken with their accounts.'
    ]
  },
  {
    title: '4. Services',
    body:
      'CyberScan detects the target CMS, offers quick (Light) or in-depth (Complete) scans, prioritizes findings, and delivers remediation-oriented dashboards and reports. All output must be interpreted by qualified security professionals.'
  },
  {
    title: '5. Pricing and Payment',
    body:
      'Unless stated otherwise, prices are quoted in euros before tax and invoiced at purchase. Licenses or subscriptions start when the service is made available. Late payments may trigger legal interest and collection fees.'
  },
  {
    title: '6. User Obligations',
    list: [
      'Provide accurate information when creating or updating an account.',
      'Ensure all files or URLs uploaded to CyberScan are free of malicious code.',
      'Notify the editor immediately of any suspected security incident or unauthorized access.'
    ]
  },
  {
    title: '7. Liability',
    body:
      'Results rely on automated models and do not guarantee the absence of vulnerabilities. The editor cannot be held liable for indirect damages, loss of revenue, or reputational harm. Total liability is limited to the fees paid during the last twelve (12) months.'
  },
  {
    title: '8. Intellectual Property',
    body:
      'The Platform, its code, UI, logos, and generated reports remain the exclusive property of the editor. Any reproduction, distribution, or exploitation without prior written consent is prohibited.'
  },
  {
    title: '9. Data Privacy',
    body:
      'Data collected through the Platform (URLs, scan results, account information) is processed solely to deliver the service and in compliance with applicable privacy regulations. Technical and organizational safeguards help preserve confidentiality.'
  },
  {
    title: '10. Term, Suspension, Termination',
    body:
      'These Terms apply for the entire duration of the service. The editor may suspend access in case of breach, fraudulent use, or unpaid invoices. Either party may terminate with 30 days’ written notice, unless an immediate termination is justified by serious misconduct.'
  },
  {
    title: '11. Updates',
    body:
      'The editor may update the Platform or these Terms. Users will be informed of meaningful changes, and continued use after notification constitutes acceptance of the updated Terms.'
  },
  {
    title: '12. Governing Law and Disputes',
    body:
      'These Terms are governed by French law. The parties shall attempt an amicable resolution within 30 days before any dispute is brought exclusively before the courts of the editor’s registered office.'
  }
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-16 px-4">
      <div className="max-w-4xl mx-auto bg-slate-900/70 backdrop-blur rounded-3xl border border-slate-800 shadow-2xl p-8 md:p-12 space-y-8">
        <header className="space-y-3">
          <p className="text-sm uppercase tracking-widest text-blue-400">CyberScan</p>
          <h1 className="text-3xl md:text-4xl font-semibold text-white">Terms of Use</h1>
          <p className="text-sm text-slate-400">Last updated: {new Date().toLocaleDateString('en-US')}</p>
        </header>

        <section className="space-y-8">
          {sections.map((section) => (
            <div key={section.title} className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6">
              <h2 className="text-xl font-semibold text-white mb-4">{section.title}</h2>
              {section.body && <p className="text-slate-300 leading-relaxed">{section.body}</p>}
              {section.list && (
                <ul className="list-disc pl-5 text-slate-300 space-y-1">
                  {section.list.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </section>

        <footer className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between text-sm text-slate-400">
          <span>Have questions? Contact your CyberScan representative.</span>
          <Link href="/register" className="text-blue-400 hover:text-blue-300 font-medium">
            Back to signup
          </Link>
        </footer>
      </div>
    </div>
  );
}
