- name: Deploy to k3s
        env:
          KUBECONFIG: /home/bi/.kube/config
        run: |
          kubectl get nodes
          kubectl rollout restart deployment frontend-pod -n cyberscan
          kubectl rollout status deployment frontend-pod -n cyberscan
